name: Build and Deploy Resy Bot

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t toestreich/resy-bot:latest .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker push toestreich/resy-bot:latest

    - name: SSH to Proxmox Server and Deploy
      run: |
        ssh user@proxmox-server-ip 'docker pull your-dockerhub-username/resy-bot:latest && docker stop resy-bot && docker rm resy-bot && docker run -d -p 3000:3000 --name resy-bot your-dockerhub-username/resy-bot:latest'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
